teleop_twist_joy_node:
  ros__parameters:
    axis_linear: {x: 1} 
    
    axis_angular: {yaw: 2} 

    scale_linear: {x: 0.5}   # 최대 전진 속도 m/s
    scale_angular: {yaw: 1.0} # 최대 회전 속도 rad/s

    enable_button: 6

    require_enable_button: true
